### ISSUE TITLE
Consumes whole ram and freeze system

### ISSUE THREAD

**Issue by gaurav10069** [bourdakos1/Custom-Object-Detection#15]
Hi you have given a very good explanation. But I have some Issue in training.
I have followed your instruction but When I run train.py with the dataset given by you my system freezes at step 0 and then I have to restart my system.
When I checked ram usage using htop command, I saw It consumes whole RAM.
I am using linux 14.04 with 8 gb, 4 CPU cores.
Can we run this code on CPU or it is only compatible to GPU?

**Comment by bourdakos1** [comment]
You should be able to run it on either CPU or GPU, but GPU will run faster. You can lower the batch size if your don't have enough RAM.
