### ISSUE TITLE
May you provide a complete example please?

### ISSUE THREAD

**Issue by Hurstwood** [bourdakos1/Custom-Object-Detection#19]
May you provide a complete example please? 

I want to attempt to utilise your project but i feel intimidated by it. I would love a complete example so i can run through it to ensure i have everything set up correctly and see how it works before i start to play.

Ps. It looks like you have a spelling mistake on line 61 in the first sentence of your readme.md. It also looks like you've merged two sentences together. It's very minor.

**Comment by bourdakos1** [comment]
For a more in depth walkthrough you can check out this post https://medium.freecodecamp.org/tracking-the-millenium-falcon-with-tensorflow-c8c86419225e
