### ISSUE TITLE
Failed to find any matching files for model.ckpt

### ISSUE THREAD

**Issue by stevewells20** [bourdakos1/Custom-Object-Detection#20]
I'm on Arch, so there could be any number of crazy problems. Followed all install instructions; while running train.py I receive:
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model.ckpt
There is a tensorflow issue currently open regarding naming conventions, but even using the full path for all of the files I still get the same error. Any ideas?

**Comment by bourdakos1** [comment]
It’s looking for the model checkpoint that you downloaded from the model zoo. You should move the files to the root directory of the repo and the path in the config should just be “model.ckpt” and it should work

**Comment by stevewells20** [comment]
Ah I see, I unpacked all of the files to the model directory, rather than splitting them between model and rootdir. The tensorflow bug with identical error messages threw me off... Thank you for the quick response! Closing as user error.

**Comment by BanuSelinTosun** [comment]
The files I have after unpacking the faster_rcnn_resnet101_coco are model.ckpt.index and model.ckpt.meta and mdoel.ckpt.data-00000-of-00001. Should I be deleting the extensions?
