### ISSUE TITLE
Problem with train.record

### ISSUE THREAD

**Issue by maylad31** [bourdakos1/Custom-Object-Detection#21]
I am geting this error:
"INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>,train.record; No such file or directory"
Please help.

**Comment by bourdakos1** [comment]
Is there a train.record file? Which command did you run when this showed up?

**Comment by maylad31** [comment]
Hi sorry for late response. Well the problem was that in the coco.config file I did not changed the paths. I provided absolute paths and problem vanished.Would providing relative paths there in the coco.config file work?Thanks once again for a very nice tutorial.

**Comment by Doan-Nguyen** [comment]
do you cmd "protoc object_detection/protos/*.proto --python_out=." & "export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim" ?
I think it can solve your problem.

**Comment by bourdakos1** [comment]
Hi @maylad31 and @Doan-Nguyen, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
