### ISSUE TITLE
When using ssd_mobilenet_v1, the object_detection_runner.py giving Value Error

### ISSUE THREAD

**Issue by BanuSelinTosun** [bourdakos1/Custom-Object-Detection#24]
This happened with at least 3 images so far and this was not the problem when these images were in the training set before.  

The error code is like this: 

Traceback (most recent call last):
  File "object_detection/object_detection_runner.py", line 90, in <module>
    detect_objects(image_path)
  File "object_detection/object_detection_runner.py", line 43, in detect_objects
    image_np = load_image_into_numpy_array(image)
  File "object_detection/object_detection_runner.py", line 39, in load_image_into_numpy_array
    (im_height, im_width, 3)).astype(np.uint8)
ValueError: cannot reshape array of size 587214 into shape (606,969,3)

It seems weird to me that these 3 images were resulting an error when doing predictions and they were completely fine when they were in the training set. Do you have any fix or suggestions for this?

Thank you,
Selin

**Comment by BanuSelinTosun** [comment]
I found the common ground in all failing images. There are 33 of them actually. All have depth of 1, in other words, they are all black and white. 
The puzzling part is still the same though, why these images are ok when they are in the train folder, and not ok when they are in the test folder. There should be an inconsistency in the code for training and predicting.

**Comment by bourdakos1** [comment]
Hi @BanuSelinTosun, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
