### ISSUE TITLE
How to train coco preset models

### ISSUE THREAD

**Issue by MichaelPanW** [bourdakos1/Custom-Object-Detection#28]
The project I am targeting is a ship.
When I try to train with your project.
Instead, the accuracy rate has dropped.
It may be because there is a similar project So affecting the weight.
Is there any way to train the original coco project
Instead of creating a new one?

**Comment by bourdakos1** [comment]
Hi @MichaelPanW, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
