### ISSUE TITLE
My own images fails

### ISSUE THREAD

**Issue by gamcoh** [bourdakos1/Custom-Object-Detection#29]
Hi nick,

I'm new to tensorflow so this may be a dumb question, but every output images that the program makes is resized to 558 of height and i think maybe that's why the program doesn't recognise features in my test images.

Maybe you can help?

**Comment by bourdakos1** [comment]
Hi @gamcoh, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems

**Comment by bourdakos1** [comment]
This could definitely be obscuring features, just keep this in mind when gathering data. If the desired object is only a few pixels in a couple thousand pixel image they might disappear when shrunk. also when one dimension is much longer than the other features may get lost.
![](https://cloud-annotations.github.io/training/object-detection/assets/image_shrink.png)

**Comment by bourdakos1** [comment]
if you want to run the image at full resolution you can try breaking the image into pieces
