### ISSUE TITLE
Inference time increases with custom model training.

### ISSUE THREAD

**Issue by asguradian** [bourdakos1/Custom-Object-Detection#32]
Compare to base model that i use for transfer learning, the model i extracted increases inference time after custom object training. is it th normal behaviour

**Comment by bourdakos1** [comment]
Hi @asguradian, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
