### ISSUE TITLE
object_detection/protos/*.proto: No such file or directory

### ISSUE THREAD

**Issue by Poonamjo** [bourdakos1/Custom-Object-Detection#33]
Getting error while compiling the protobuf libraries

**Comment by bourdakos1** [comment]
Make sure the directory is in your python path

**Comment by Poonamjo** [comment]
after running the command 
protoc object_detection/protos/*.proto --python_out=.
I am getting below output 
'protoc' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Poonamjo** [comment]
I added the directory for protoc.exe to my System variable PATH.
But still I am facing the issue object_detection/protos/*.proto: No such file or directory
What else needs to be done?

**Comment by Poonamjo** [comment]
after executing the command 
python object_detection/create_tf_record.py

I am facing the issue
Traceback (most recent call last):
  File "object_detection/create_tf_record.py", line 39, in <module>
    from object_detection.utils import dataset_util
ModuleNotFoundError: No module named 'object_detection'

**Comment by bourdakos1** [comment]
The protobufs are already compiled, so you shouldn’t have to run that command unless you are changing the protobuf code.

As for the second issue, did you add the object detection directory to your path?

**Comment by bourdakos1** [comment]
This is my bad, I need to update the instructions. You can follow along with this article: https://link.medium.com/3giFefOgWS

It should have the updated instructions. I’ll try and fix up the readme

**Comment by Poonamjo** [comment]
I was ae to resolve the above issues. Thanks 
Need another help
I want to train the model resnet50_coco_best_v2.1.0.h5 for radiator images
I have prepared the tf record files for train and testing.
Can you suggest some help?
Regarding its pipeline config, checkpoint and all
Please guide

**Comment by bourdakos1** [comment]
Hi @Poonamjo, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
