### ISSUE TITLE
WARNING:root:Could not find annotations/xmls/

### ISSUE THREAD

**Issue by jeromesteve202** [bourdakos1/Custom-Object-Detection#36]
I was following your article on Medium and everything went well up until where I had to run `python object_detection/create_tf_record.py` I have updated my `trainval.txt` and `label_map.pbtxt`. I also have my xml files in the folder where they are supposed to be also with the corresponding images in the images folder. However, whenever I try to run the create_tf_record.py file, it keeps giving me an error saying cannot find annotations. I am not sure what I am doing wrong. Please let me know if this can be fixed

**Comment by bourdakos1** [comment]
Hi @jersteve, this repo relies on a dated version of the TensorFlow api. We've moved to a more future proof version here: https://github.com/cloud-annotations/training
I encourage you to try it out and reopen this issue there if you are still running into problems
