### ISSUE TITLE
why is it asking for trimaps ?

### ISSUE THREAD

**Issue by skywo1f** [bourdakos1/Custom-Object-Detection#39]
I thought the point of having an images folder and an annotations folder was that that was all the required information for the network to train. But looking at step 6 of 
https://towardsdatascience.com/custom-object-detection-using-tensorflow-from-scratch-e61da2e10087

create_tf_record needs a trimaps folder as well. Also apparently create_tf_record is not compatible with jpg's? as it is only hardcoded to accept png's

**Comment by bourdakos1** [comment]
If you are trying to create an object detection model, I recommend following this tutorial https://docs.annotations.ai/workshops/object-detection/

I think trimaps are used for image segmentation and regarding jpgs vs pngs, I believe the tensorflow object detection api only supports jpgs
