### ISSUE TITLE
Warnings when running create_tf_record.py

### ISSUE THREAD

**Issue by jetzzze** [bourdakos1/Custom-Object-Detection#5]
Hi Nick, I am not sure if I am doing wrong. Running "python object_detection/create_tf_record.py" gives a warning but train.record and val.record are created:

dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin_x86_64/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal.so___Utensorflow in /Users/jre/Library/Python/2.7/lib/python/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so being ignored in restricted program because it is a relative path
/Users/jre/Downloads/Watson/Custom-Object-Detection-master/object_detection/utils/dataset_util.py:75: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not xml:
[ /Users/jre/Downloads/Watson/Custom-Object-Detection-master ]
jre@ibm-jre-mbp  ==_-+- 

Is this ok?

**Comment by bourdakos1** [comment]
Yea, thats just a warning. It shouldn't affect anything
